name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-debug:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: cmake
      run: cmake -B build -D CMAKE_BUILD_TYPE=Debug
    - name: build
      run: make -C build all
    - name: test
      run: make -C build test
