name: Web UI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: mymindstorm/setup-emsdk@v14
    - run: emcc -v
    - name: Compile C++ to Wasm+Javascript using Emscripten
      run: ./build-wasm-api.sh
